embedding_size: 64
hidden_size_list: [64,64,64]
node_dropout: 0.0
message_dropout: 0.1
reg_weight: 1e-5
data_path: /data7_8T/ycx/tmp/Recbole_STRec/RecBole-GNN/data/
# dataset: Amazon_Books

metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision', 'ItemCoverage', 'GiniIndex', 'ShannonEntropy', 'TailPercentage']
topk: [5, 10, 20]
seed: 42
#eval_args:
#    split: {'RS': [0.7,0.1,0.2]}
train_neg_sample_args:
    uniform: 1

epochs: 50
stopping_step: 5
learning_rate: 0.005 # A0.01 S 0.005 Y0.005