# WARNING:
# 1. if you set inter_matrix_type='rating', you must set `unused_col: ~` in your data config files.
# 2. The dimensions of the last layer of users and items must be the same

inter_matrix_type: '01'         # (str) Type of interaction matrix. Range in ['01', 'rating'].
user_embedding_size: 64         # (int) The initial embedding size of users.
item_embedding_size: 64         # (int) The initial embedding size of items.
user_hidden_size_list: [64, 64] # (list of int) The hidden size of each layer in MLP for users.
item_hidden_size_list: [64, 64] # (list of int) The hidden size of each layer in MLP for items.
embedding_size: 10              # (int) The embedding size of features.

######
data_path: /data7_8T/ycx/tmp/Recbole_STRec/RecBole-GNN/data/
# dataset: Amazon_Books
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision', 'ItemCoverage', 'GiniIndex', 'ShannonEntropy', 'TailPercentage']
topk: [5, 10, 20]
seed: 42
#eval_args:
#    split: {'RS': [0.6,0.2,0.2]}
train_neg_sample_args:
    uniform: 1